name: Laravel (PROD)

on:
  workflow_dispatch

jobs:
  laravel-deploy-production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    environment:
      name: production

    steps:
    - uses: actions/checkout@v2

    - name: Run composer install
      run: composer install -n --prefer-dist
    
    - name: Setup PHP
      uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd
        coverage: none
    
    - name: Cache PHP dependencies
      uses: actions/cache@v1
      with:
        path: vendor
        key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
    
    - name: Install Composer Dependencies
      run: composer install -q --optimize-autoloader --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

    - name: Create .env file
      run: |
        echo "APP_KEY=" >> .env
        echo "APP_DEBUG=false" >> .env
        echo "APP_ENV=production" >> .env
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=${{ vars.DB_DATABASE }}" >> .env
        echo "DB_USERNAME=${{ vars.DB_USERNAME }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "VITE_API_BASE_URL=https://dabiu-api.duite.com.ar" >> .env
    
    - name: Create public .env file
      run: |
        echo "BASE_PATH=/../../dabiu-api" >> public/.env
    
    - name: Build Node
      run: |
        npm install
        npm run build
    
    - name: Generate Key
      run: php artisan key:generate

    - name: Cache setting
      run: |
        php artisan config:clear
        php artisan cache:clear
    
    - name: Deploy API
      uses: AEnterprise/rsync-deploy@v1.0.2
      env:
        DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-e -c -r --delete"
        SERVER_PORT: ${{ vars.SSH_PORT }}
        FOLDER: "./"
        SERVER_IP: ${{ vars.SSH_HOST }}
        USERNAME: ${{ vars.SSH_USER }}
        SERVER_DESTINATION: "domains/duite.com.ar/dabiu-api"
    
    - name: Deploy public folder
      uses: AEnterprise/rsync-deploy@v1.0.2
      env:
        DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-e -c -r --delete"
        SERVER_PORT: ${{ vars.SSH_PORT }}
        FOLDER: "./public/"
        SERVER_IP: ${{ vars.SSH_HOST }}
        USERNAME: ${{ vars.SSH_USER }}
        SERVER_DESTINATION: "domains/duite.com.ar/public_html/dabiu"